/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EWEBVIEW_AUTODEFS_H
#define S3EWEBVIEW_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_WEBVIEW_NAME "s3eWebView"
#define S3E_EXT_WEBVIEW_HASH 0x2c4bb889

#endif /* !S3EWEBVIEW_AUTODEFS_H */
